version: "3"
volumes:
  node_modules:
  build:
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    environment:
      - MIX_ENV=docker
      - PORT=80
    ports:
      - "80:80"
    depends_on:
      - postgres
