version: "3"
volumes:
  node_modules:
  build:
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: mix do ecto.create, ecto.migrate
    ports:
      - "8000:8000"
    depends_on:
      - postgres
